language: php

php:
    - 7.1
    - 7.2

before_install:
    - travis_retry composer self-update

install:
    - travis_retry composer install --no-interaction --prefer-dist

script:
    - vendor/bin/phpunit --coverage-clover=coverage.xml

matrix:
    fast_finish: true

after_success:
- bash <(curl -s https://codecov.io/bash)
